<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            ['name' => '50 Shades of Pink', 'description' => 'Bó hoa hồng pastel phối astilbe hồng, vẻ nhẹ nhàng – sang trọng, lý tưởng cho sinh nhật và kỷ niệm.', 'size' => 'Vừa', 'wrapping' => 'Giấy lụa hồng nhạt, ruy băng satin', 'care' => 'Cắt gốc hoa và thay nước mỗi 2 ngày. Tránh ánh nắng trực tiếp.', 'price' => 350000, 'image_url' => 'images/50ShadesOfPink.jpeg', 'is_visible' => true],
            ['name' => 'A Brighter Day', 'description' => 'Hoa hồng tím oải hương được sắp trong hộp acrylic tròn trong suốt, tượng trưng cho sự sang trọng và bí ẩn.', 'size' => 'Vừa', 'wrapping' => 'Hộp acrylic trong suốt có nắp', 'care' => 'Đổ nước vào khoang hộp mỗi ngày, giữ mực nước ngang cuống; đặt nơi mát, tránh nắng và điều hòa thổi trực tiếp.', 'price' => 420000.00, 'image_url' => 'images/ABrighterDay.jpg', 'is_visible' => true],
            ['name' => 'A Summer Love', 'description' => 'Bình hoa tông nhiệt đới rực rỡ với mix hoa dại vàng và họ lily/cam–hồng, tạo điểm nhấn tươi mới cho không gian.', 'size' => 'Vừa', 'wrapping' => 'Bình gốm tròn cao màu cam đỏ, không giấy gói', 'care' => 'Thay nước mỗi ngày, cắt xéo gốc 1–2 cm, đặt nơi mát tránh nắng gắt.', 'price' => 560000, 'image_url' => 'images/ASummerLove.jpg', 'is_visible' => true],
            ['name' => 'Beauty And The Dates', 'description' => 'Hoa hồng fuchsia trên thân gỗ, phối hộp quà chà là, tạo set quà sang trọng và độc đáo.', 'size' => 'Vừa', 'wrapping' => 'Chậu vuông đen logo vàng, phủ sỏi đen; kèm hộp chà là', 'care' => 'Giữ bọt/xốp ẩm bằng cách châm nước nhẹ mỗi ngày, đặt nơi mát tránh nắng và gió máy lạnh.', 'price' => 490000, 'image_url' => 'images/BeautyAndTheDates.jpg', 'is_visible' => true],
            ['name' => 'Black Swan', 'description' => 'Hộp hoa tone trắng – đen tối giản: hồng trắng đồng điệu điểm 1 nhành lan hồ điệp trắng, sang trọng tinh khiết.', 'size' => 'Vừa', 'wrapping' => 'Hộp tròn đen tay cầm, logo vàng; không giấy gói', 'care' => 'Châm nước cho xốp ẩm mỗi ngày; tránh nắng và gió điều hòa trực tiếp, lau khô cánh lan nếu bị đọng nước.', 'price' => 590000, 'image_url' => 'images/BlackSwan.jpg', 'is_visible' => true],
            ['name' => 'Bombastic', 'description' => 'Bó hoa hồng chùm pastel khối lớn, tán tròn đầy, phong cách thanh lịch tối giản.', 'size' => 'Lớn', 'wrapping' => 'Giấy kraft nâu – xám kiểu layer, túi trắng tay ruy băng', 'care' => 'Cắm bình ngay sau khi nhận, thay nước mỗi ngày và cắt xéo gốc 1–2 cm, tránh nắng gắt.', 'price' => 690000, 'image_url' => 'images/Bombastic.jpg', 'is_visible' => true],
            ['name' => 'Bubble Gum', 'description' => 'Bó cẩm tú cầu hồng pastel mềm mại, tán tròn bồng bềnh như kẹo gum – ngọt ngào, tinh tế.', 'size' => 'Lớn', 'wrapping' => 'Giấy trắng – xám tối giản, túi trắng tay ruy băng', 'care' => 'Cắm bình nước mát ngay khi nhận, thay nước hằng ngày; phun sương nhẹ lên cánh để giữ độ ẩm, tránh nắng gắt.', 'price' => 570000, 'image_url' => 'images/BubbleGum.jpg', 'is_visible' => true],
            ['name' => 'Earthy Enigma', 'description' => 'Bó hoa mang phong vị rustic – thu vàng: gồm cẩm tú cầu màu beige, thược dược đỏ mận, lá bạch đàn nhuộm đồng, kết hợp cùng cỏ pampas và hoa dại, gợi cảm giác ấm áp và mộc mạc của mùa thu.', 'size' => 'Lớn', 'wrapping' => 'Bình giỏ mây đan tự nhiên, không giấy gói', 'care' => 'Giữ nước trong bình luôn đầy 2/3, thay nước mỗi ngày; đặt nơi thoáng mát, tránh nắng và gió máy lạnh trực tiếp.', 'price' => 770000, 'image_url' => 'images/EarthyEnigma.jpg', 'is_visible' => true],
            ['name' => 'Eclipse', 'description' => 'Bó hoa mang tông trầm hiện đại: gồm cẩm tú cầu tím rượu vang kết hợp cùng mẫu đơn hoặc hoa vườn màu cam đào, lá khô và cỏ pampas, tạo điểm nhấn rustic đầy tinh tế.', 'size' => 'Vừa', 'wrapping' => 'Bình đá mài màu kem, không giấy gói', 'care' => 'Giữ nước 2/3 bình, thay nước mỗi ngày; đặt nơi mát, tránh nắng và gió điều hòa thổi trực tiếp.', 'price' => 534000, 'image_url' => 'images/Eclipse.jpg', 'is_visible' => true],
            ['name' => 'Emily', 'description' => 'Hộp hoa thanh lịch: nền cẩm tú cầu hồng pastel điểm hai bông lan hồ điệp tím, sắc tím – hồng nổi bật.', 'size' => 'Vừa', 'wrapping' => 'Hộp tròn trắng logo vàng; không giấy gói', 'care' => 'Châm nước vào xốp mỗi ngày; đặt nơi mát, tránh nắng và gió điều hòa; lau khô cánh lan nếu đọng nước.', 'price' => 650000, 'image_url' => 'images/Emily.jpg', 'is_visible' => true],
            ['name' => 'End Of The Rainbow', 'description' => 'Hộp hoa phối màu dịu: cẩm tú cầu xanh baby, hồng trắng kem, cát tường hồng đậm – xanh non, điểm lá bạc eucalyptus.', 'size' => 'Vừa', 'wrapping' => 'Hộp tròn trắng logo vàng; không giấy gói', 'care' => 'Châm nước vào xốp mỗi ngày; đặt nơi mát thoáng, tránh nắng và gió điều hòa thổi trực tiếp.', 'price' => 558000, 'image_url' => 'images/EndOfTheRainbow.jpg', 'is_visible' => true],
            ['name' => 'Fairytale Ending', 'description' => 'Hộp hoa cổ tích tông hồng: cẩm tú cầu hồng đào, hồng hồng, lan hồ điệp trắng và phụ liệu khô hồng tím, vừa ngọt ngào vừa hiện đại.', 'size' => 'Vừa', 'wrapping' => 'Hộp tròn kem tối giản; không giấy gói', 'care' => 'Châm nước vào xốp mỗi ngày; đặt nơi mát, tránh nắng và gió điều hòa; không phun sương trực tiếp lên cánh lan.', 'price' => 648000, 'image_url' => 'images/FairytaleOfTheRainbow.jpg', 'is_visible' => true],
            ['name' => 'Garden Of Gratitude', 'description' => 'Bó hoa tông xanh – tím pastel thanh mát: delphinium xanh, hồng kem, cát tường tím và viburnum xanh, điểm lá bạc eucalyptus.', 'size' => 'Vừa', 'wrapping' => 'Giấy kraft nâu phối giấy trắng, túi trắng logo vàng', 'care' => 'Cắm bình ngay sau khi nhận, thay nước mỗi ngày và cắt xéo gốc 1–2 cm; tránh nắng gắt và gió điều hòa.', 'price' => 878000, 'image_url' => 'images/GardenOfGratitude.jpg', 'is_visible' => true],
            ['name' => 'Golden Glow', 'description' => 'Bó hoa rực rỡ tông vàng – cam: hồng vàng, hồng cam, cát tường trắng và craspedia, điểm nhụy sao biển bạc.', 'size' => 'Vừa', 'wrapping' => 'Giấy lụa trắng, túi trắng logo vàng; không nơ hoặc nơ satin trắng', 'care' => 'Cắm bình ngay sau khi nhận, thay nước mỗi ngày và cắt xéo gốc 1–2 cm; tránh nắng gắt.', 'price' => 518000, 'image_url' => 'images/GlodenGlow.jpg', 'is_visible' => true],
            ['name' => 'Green Goddess', 'description' => 'Bó xanh – trắng thanh khiết: cẩm tú cầu xanh lá, hồng trắng, stock trắng, viburnum xanh và lá bạc eucalyptus.', 'size' => 'Vừa', 'wrapping' => 'Giấy lụa trắng, túi trắng logo vàng; không nơ hoặc nơ satin trắng', 'care' => 'Cắm bình ngay sau khi nhận, thay nước mỗi ngày và cắt xéo gốc 1–2 cm; tránh nắng gắt và gió điều hòa.', 'price' => 718000, 'image_url' => 'images/GreenGoddess.jpg', 'is_visible' => true],
            ['name' => 'Home Sweet Home', 'description' => 'Chậu lan hồ điệp trắng tinh khôi, dáng 2–3 cần hoa, đặt trong hộp đen sang trọng – bền đẹp, dễ chăm.', 'size' => 'Vừa', 'wrapping' => 'Chậu/hộp vuông đen logo vàng, lót vỏ thông; không giấy gói', 'care' => 'Tưới 7–10 ngày/lần bằng phun sương gốc hoặc ngâm chậu 10 phút, để nơi sáng tán xạ, tránh nắng gắt và gió lạnh trực tiếp.', 'price' => 748000, 'image_url' => 'images/HomeSweetHome.jpg', 'is_visible' => true],
            ['name' => 'Magnificent Muse', 'description' => 'Bó hoa tông terracotta ấm áp: gồm hoa hồng cam đất, anthurium nâu cam, stock trắng và cỏ pampas, được phối cùng giấy gói nâu – hồng đất, mang lại cảm giác ấm áp và thanh lịch đậm sắc thu.', 'size' => 'Vừa', 'wrapping' => 'Giấy kraft nâu phối hồng đất, bó đáy buộc nơ satin trắng, túi trắng logo vàng', 'care' => 'Cắm bình ngay sau khi nhận, thay nước mỗi ngày và cắt xéo gốc 1–2 cm; tránh nắng gắt và gió lạnh trực tiếp.', 'price' => 747000, 'image_url' => 'images/MagnificentMuse.jpg', 'is_visible' => true],
            ['name' => 'Midnight Moon', 'description' => 'Chậu lan hồ điệp trắng mini dáng thanh, đặt trong khối vuông acrylic trong suốt lót vỏ thông – trang nhã, gọn bàn.', 'size' => 'Nhỏ', 'wrapping' => 'Chậu vuông acrylic trong, lót vỏ thông; không giấy gói', 'care' => 'Tưới 7–10 ngày/lần bằng ngâm chậu 5–10 phút, để nơi sáng tán xạ, thoáng gió, tránh nắng trực tiếp và gió lạnh.', 'price' => 429000, 'image_url' => 'images/MidnightMoon.jpg', 'is_visible' => true],
            ['name' => 'Moonlight', 'description' => 'Bó hoa phối trắng – hồng – tím nhã nhặn: cẩm tú cầu trắng, hồng kem, hồng hồng, cát tường và astilbe hồng, điểm lá eucalyptus.', 'size' => 'Vừa', 'wrapping' => 'Giấy trắng tối giản, túi trắng tay ruy băng', 'care' => 'Cắm bình ngay sau khi nhận, thay nước mỗi ngày và cắt xéo gốc 1–2 cm; tránh nắng gắt và gió điều hòa.', 'price' => 357000, 'image_url' => 'images/Moonlight.jpg', 'is_visible' => true],
            ['name' => 'Morning Mist', 'description' => 'Hộp hoa tông xanh pastel – kem dịu mát: cẩm tú cầu kem, hồng xanh baby, hồng tím nhạt và phụ liệu xanh lam độc đáo.', 'size' => 'Vừa', 'wrapping' => 'Hộp tròn kem tối giản; không giấy gói', 'care' => 'Châm nước vào xốp mỗi ngày; đặt nơi mát thoáng, tránh nắng gắt và gió điều hòa thổi trực tiếp.', 'price' => 757000, 'image_url' => 'images/MorningMist.jpg', 'is_visible' => true],
            ['name' => 'Peace And Harmony', 'description' => 'Hộp hoa xanh – trắng thanh khiết: hồng kem, cát tường trắng, cẩm tú cầu xanh lá điểm thistle bạc và lá eucalyptus.', 'size' => 'Vừa', 'wrapping' => 'Hộp vuông trắng logo vàng; không giấy gói', 'care' => 'Châm nước vào xốp mỗi ngày; đặt nơi mát thoáng, tránh nắng gắt và gió điều hòa thổi trực tiếp.', 'price' => 512000, 'image_url' => 'images/PeaceAndHarmony.jpg', 'is_visible' => true],
            ['name' => 'Petals And Pralines', 'description' => 'Set quà ngọt ngào: hộp hoa hồng pastel phối astilbe hồng, kèm hộp praline/chocolate tông đồng điệu – tinh tế, lãng mạn.', 'size' => 'Vừa', 'wrapping' => 'Hộp vuông trắng logo vàng; kèm hộp chocolate ruy băng trắng', 'care' => 'Châm nước vào xốp mỗi ngày; bảo quản chocolate nơi khô mát, tránh nắng và nhiệt cao.', 'price' => 452000, 'image_url' => 'images/PetalsAndPralines.jpg', 'is_visible' => true],
            ['name' => 'Spring Symphony', 'description' => 'Hộp hoa hồng chùm hồng fuchsia khối lớn, tán bán cầu rực rỡ – nổi bật mọi không gian.', 'size' => 'Vừa', 'wrapping' => 'Hộp vuông trắng logo vàng', 'care' => 'Châm nước vào xốp mỗi ngày; đặt nơi mát thoáng, tránh nắng gắt và gió điều hòa.', 'price' => 721000, 'image_url' => 'images/SpringSymphony.jpg', 'is_visible' => true],
            ['name' => 'Sultry Silhouette', 'description' => 'Bình hoa cảm hứng thu: thược dược hồng phấn – cam cháy, cỏ pampas bồng bềnh, lá phong vàng cam – ấm áp, ấn tượng.', 'size' => 'Lớn', 'wrapping' => 'Bình gốm màu kem vân đá, không giấy gói', 'care' => 'Giữ nước 2/3 bình, thay nước mỗi ngày; đặt nơi mát, tránh nắng gắt và gió lạnh trực tiếp.', 'price' => 839000, 'image_url' => 'images/SultrySilhouette.jpg', 'is_visible' => true],
            ['name' => 'Surreal Sunrise', 'description' => 'Bó hoa cam – vàng tươi vui: hồng garden cam đào, hồng vàng, veronica xanh và cúc họa mi nhỏ, điểm lá eucalyptus.', 'size' => 'Vừa', 'wrapping' => 'Giấy trắng tối giản, túi trắng logo vàng', 'care' => 'Cắm bình ngay sau khi nhận, thay nước mỗi ngày và cắt xéo gốc 1–2 cm; tránh nắng gắt và gió điều hòa.', 'price' => 399000, 'image_url' => 'images/SurrealSunrise.jpg', 'is_visible' => true],
            ['name' => 'Whistling Winds', 'description' => 'Chậu lan oncidium vàng ‘vũ nữ’ nhiều cần, nở rực rỡ, dáng mềm mại như vũ điệu.', 'size' => 'Lớn', 'wrapping' => 'Chậu sứ nghệ thuật vân sóng, phủ rêu trang trí; không giấy gói', 'care' => 'Tưới 5–7 ngày/lần giữ ẩm giá thể, đặt nơi sáng tán xạ, thoáng gió; tránh nắng gắt và úng nước.', 'price' => 719000, 'image_url' => 'images/WhistlingWinds.jpg', 'is_visible' => true],
            ['name' => 'White Swan', 'description' => 'Set quà trang nhã: chậu lan hồ điệp trắng 1 cần kèm hộp chà là cao cấp – tối giản mà tinh tế.', 'size' => 'Vừa', 'wrapping' => 'Chậu vuông trắng logo vàng, lót vỏ thông; hộp quà đen ruy băng', 'care' => 'Lan: tưới 7–10 ngày/lần bằng ngâm chậu 5–10 phút, đặt nơi sáng tán xạ; Chà là: bảo quản nơi khô mát, đậy kín sau khi mở.', 'price' => 839000, 'image_url' => 'images/WhiteSwan.jpg', 'is_visible' => true],
            ['name' => 'Fuchsia Fury', 'description' => 'Bình cao tông hồng – fuchsia rực rỡ: thược dược đa sắc, hoa vườn hồng cánh tia và phụ liệu hồng tím, dáng tỏa nghệ thuật.', 'size' => 'Lớn', 'wrapping' => 'Bình trụ men hồng phấn, không giấy gói', 'care' => 'Giữ nước 2/3 bình, thay nước mỗi ngày; đặt nơi mát thoáng, tránh nắng gắt và gió điều hòa trực tiếp.', 'price' => 639000, 'image_url' => 'images/FuchsiaFury.jpg', 'is_visible' => true],
        ]);
    }
}

